### ISSUE TITLE
Android 4.2.1 已经root的xposed使用这个插件无法自动抢红包

### ISSUE THREAD

**Issue by atmouse-** [veryyoung/WechatLuckyMoney#101]
Xposed框架版本 
app_process 58
XposedBridge.jar 54
微信版本 6.5.4 Google play 安装的

这是xposed的日志

’’’Found wechat version:6.5.4
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1300(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5338)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:217)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/luckymoney/c/ae
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.c.ae" on path: DexPathList[dexElements=[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 23 more
Found wechat version:6.5.4
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1300(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5338)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:217)
	at external.org.apache.commons.lang3.ClassUtils.getClass(C
’’’

**Comment by atmouse-** [comment]
忘了说了 weichatluchymoney版本是 1.2.5

**Comment by uchen1225** [comment]
hi,i want to know will you update wechatluckymoney for wechat 6.5.7.
thanks for you hard work.

**Comment by walaoaaa1234** [comment]
https://github.com/veryyoung/WechatLuckyMoney/issues/69#issuecomment-274329190
@uchen1225

**Comment by atmouse-** [comment]
看来并不打算解决

**Comment by wzlu** [comment]
我好像是类似问题
