### ISSUE TITLE
6.5.8 不能运行

### ISSUE THREAD

**Issue by uojo** [veryyoung/WechatLuckyMoney#110]
2017年5月27日 上午2:26:08 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'Xiaomi/dior/dior:4.4.4/KTU84P/V8.1.1.0.KHICNDI:user/release-keys'
Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1.apk
  Loading class me.veryyoung.wechat.luckymoney.Main
Found wechat version:6.5.8
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/luckymoney/c/ae
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.c.ae" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 23 more

**Comment by godboy0913** [comment]
我之前是微信6.5.6，搭配1.2.5的是正常的
看到有新版本1.2.6，并且适配6.5.8，就先将1.2.5里所有功能都关闭，再在xposed里将1.2.5停用，重启手机，升级微信到6.5.8，升级插件到1.2.6，重启，到xposed里启用插件，重启，进插件开启抢红包的各种功能？我以前升级也碰到过插件失效的问题，后来就根据这个流程操作，都可以正常使用了，但这次不行
发现快速拆包跟显示微信ID是正常的，唯独不会自动抢红包，延时关闭也不抢
我就又按照上面的来，折腾了几次，依旧
然后停用插件，重启，卸载，重启，安装重启，启用，重启，还是一样不会抢，不知道问题出在哪里了
有人帮帮我吗？或者交流下，你们是怎么操作升级的？或者指点下，我哪做的不对？

**Comment by godboy0913** [comment]
微信降到6.5.6，插件能正常工作了，这你为什么没人来讨论回复的呀

**Comment by xiaozhucdj** [comment]
@godboy0913 我按照你的降到6.5.6也不行啊。用的1.2.6，还有其他的办法吗
