### ISSUE TITLE
oppo A31c抢不了，xposed日志如下

### ISSUE THREAD

**Issue by EricBigGod** [veryyoung/WechatLuckyMoney#152]
Found wechat version:6.5.23
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.collect.reward.ui.QrRewardSelectMoneyUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.DonateHook.hook(Unknown Source)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:143)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.collect.reward.ui.QrRewardSelectMoneyUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/collect/reward/ui/QrRewardSelectMoneyUI
	... 24 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.collect.reward.ui.QrRewardSelectMoneyUI" on path: DexPathList[[zip file "/data/app/com.tencent.mm-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-2, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more

**Comment by Freedom000** [comment]
安卓系统版本多少？

**Comment by EricBigGod** [comment]
华为P6移动版也是这个错误，系统版本4.4.2

**Comment by veryyoung** [comment]
@EricBigGod 微信版本比较旧了，升级到 6.6.1 吧

**Comment by EricBigGod** [comment]
我是用的6.5.23版本的微信啊，我再升级下试试。

**Comment by EricBigGod** [comment]
报微信的另外一个类找不到了，

**Comment by EricBigGod** [comment]
2018年1月3日 09:47:39 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'P6-T00V100R001C01B708' with fingerprint 'Huawei/P6-T00/hwp6-t00:4.4.2/HuaweiP6-T00/C01B708:user/ota-rel-keys,release-keys'
Loading modules from /data/app/com.deified.robot.auotorobot-1.apk
  Loading class com.deified.robot.auotorobot.XposedMain
Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1.apk
  Loading class me.veryyoung.wechat.luckymoney.Main
WeChat versionName:6.6.1 versionCode:1220
Found wechat version:6.6.1
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.DonateHook.hook(Unknown Source)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5253)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 20 more

**Comment by EricBigGod** [comment]
插件是刚去酷安市场下载的

**Comment by veryyoung** [comment]
@EricBigGod 这个类是肯定存在的，建议安装完重启下手机
