### ISSUE TITLE
还是不行啊？求大神帮忙看看，日志如下

### ISSUE THREAD

**Issue by feierpusi** [veryyoung/WechatLuckyMoney#165]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)	... 24 more

**Comment by veryyoung** [comment]
@feierpusi 没有提供任何有价值的日志
