### ISSUE TITLE
.ClassNotFoundException: com.tencent.mm.ui.LauncherUI

### ISSUE THREAD

**Issue by tomsean** [veryyoung/WechatLuckyMoney#194]
Loading Xposed v54 (for Zygote)...
Running ROM 'MLA-AL10-user 4.4.2 HUAWEIMLA-AL10 381180224 release-keys' with fingerprint 'HUAWEI/MLA-AL10/HWMLA:4.4.2/HUAWEIMLA-AL10/381180224:user/release-keys'
Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1.apk
  Loading class me.veryyoung.wechat.luckymoney.Main
Found wechat version:6.6.5
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.DonateHook.hook(Unknown Source)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/ui/LauncherUI
	... 24 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.ui.LauncherUI" on path: DexPathList[[zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more
Found wechat version:6.6.5
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.DonateHook.hook(Unknown Source)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/ui/LauncherUI
	... 24 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.ui.LauncherUI" on path: DexPathList[[zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more
Found wechat version:6.6.5
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.DonateHook.hook(Unknown Source)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/ui/LauncherUI
	... 24 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.ui.LauncherUI" on path: DexPathList[[zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more
Found wechat version:6.6.5
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.DonateHook.hook(Unknown Source)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5019)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/ui/LauncherUI
	... 24 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.ui.LauncherUI" on path: DexPathList[[zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 24 more

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
