### ISSUE TITLE
No Such Method: LuckyMoneyReceiveUI

### ISSUE THREAD

**Issue by cxy1997** [veryyoung/WechatLuckyMoney#234]
```
02-04 19:43:15.276 I/Xposed  (23233): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
02-04 19:43:15.454 I/Xposed  (23233): Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1/base.apk
02-04 19:43:15.469 I/Xposed  (23233):   Loading class me.veryyoung.wechat.luckymoney.Main
02-04 19:43:57.089 I/Xposed  (25602): Found wechat version:6.7.3
02-04 19:43:57.233 E/Xposed  (25602): java.lang.NoSuchMethodError: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI#c(int,int,java.lang.String,com.tencent.mm.ah.m)#exact
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
02-04 19:43:57.233 E/Xposed  (25602): 	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
02-04 19:43:57.233 E/Xposed  (25602): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-04 19:43:57.233 E/Xposed  (25602): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-04 19:43:57.233 E/Xposed  (25602): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
02-04 19:43:57.233 E/Xposed  (25602): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-04 19:43:57.233 E/Xposed  (25602): 	at android.os.Looper.loop(Looper.java:154)
02-04 19:43:57.233 E/Xposed  (25602): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-04 19:43:57.233 E/Xposed  (25602): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 19:43:57.233 E/Xposed  (25602): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-04 19:43:57.233 E/Xposed  (25602): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-04 19:43:57.233 E/Xposed  (25602): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```
Wechat version: 6.7.3

**Comment by cxy1997** [comment]
After updating wechat to 7.0.0, 
```
02-04 20:32:51.160 I/Xposed  (13555): Found wechat version:7.0.0
02-04 20:32:51.182 E/Xposed  (13555): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.b.ag
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
02-04 20:32:51.182 E/Xposed  (13555):  at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
02-04 20:32:51.182 E/Xposed  (13555):  at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-04 20:32:51.182 E/Xposed  (13555):  at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-04 20:32:51.182 E/Xposed  (13555):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
02-04 20:32:51.182 E/Xposed  (13555):  at android.os.Handler.dispatchMessage(Handler.java:102)
02-04 20:32:51.182 E/Xposed  (13555):  at android.os.Looper.loop(Looper.java:154)
02-04 20:32:51.182 E/Xposed  (13555):  at android.app.ActivityThread.main(ActivityThread.java:6186)
02-04 20:32:51.182 E/Xposed  (13555):  at java.lang.reflect.Method.invoke(Native Method)
02-04 20:32:51.182 E/Xposed  (13555):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-04 20:32:51.182 E/Xposed  (13555):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-04 20:32:51.182 E/Xposed  (13555): Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.b.ag
02-04 20:32:51.182 E/Xposed  (13555):  at java.lang.Class.classForName(Native Method)
02-04 20:32:51.182 E/Xposed  (13555):  at java.lang.Class.forName(Class.java:400)
02-04 20:32:51.182 E/Xposed  (13555):  at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
02-04 20:32:51.182 E/Xposed  (13555):  at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
02-04 20:32:51.182 E/Xposed  (13555):  ... 17 more
02-04 20:32:51.182 E/Xposed  (13555): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.b.ag" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.mm-2/lib/arm, /data/app/com.tencent.mm-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
02-04 20:32:51.182 E/Xposed  (13555):  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-04 20:32:51.182 E/Xposed  (13555):  at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
02-04 20:32:51.182 E/Xposed  (13555):  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-04 20:32:51.182 E/Xposed  (13555):  ... 21 more
```
