### ISSUE TITLE
插件加载过程报错

### ISSUE THREAD

**Issue by ouyangde** [veryyoung/WechatLuckyMoney#73]
Xposed日志如下，我用的红包模块版本是1.2.3。
> Found wechat version:6.5.3
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1800(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/luckymoney/ui/LuckyMoneyReceiveUI
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-2, /vendor/lib, /system/lib, /data/datalib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 23 more

这应该是快速拆包的Hook抛出异常，所以后面的查看wechat ID的功能也用不了。

**Comment by veryyoung** [comment]
@ouyangde 使用新版的插件吧。
