### ISSUE TITLE
2月7号更新后使用不了

### ISSUE THREAD

**Issue by aabb5605** [veryyoung/WechatLuckyMoney#82]
更新后使用不了   不会自动开包   QQ更新后的可以自动开包-微信更新后不可以   请问大神什么问题、新年快乐大师

**Comment by veryyoung** [comment]
亲测可行的哦，你升级完试过重启了没有？

**Comment by aabb5605** [comment]
重新好多次   重新安装过微信   和安装过  2月7最新版    都不行

**Comment by aini10000na** [comment]
我的升级后也不行了，xposed版本是2.6.1，红米手机Android4.4.4,MIUI8

**Comment by aini10000na** [comment]
附上xposed日志

Found wechat version:6.5.4
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/luckymoney/c/ae
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.c.ae" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-2, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 23 more

**Comment by SMArice** [comment]
@veryyoung  有这么一两个问题，红包抢一下就不抢了。过一下又开始，抢了几个又不抢了。BUG希望修复下。PS微信捐赠没反应了

**Comment by veryyoung** [comment]
@SMArice 你这个好像版本错了吧....微信和插件都用最新版吧

**Comment by SMArice** [comment]
@veryyoung  我的微信6.5.4，最新版。本来没想升级的，看你的插件支持6.5.4我就升级了微信。结果不能用，断断续续的，抢几个又不会抢了

**Comment by LongerPro** [comment]
@veryyoung 
我的貌似更惨，忘了哪天开始，所有的都不能抢了，这中间手机没升级系统，没做什么设置的更改。
微信从6.5.4降回6.5.3，xposed版本是3.0.1，小米4c Android5.1.1 MIUI8

**Comment by walaoaaa1234** [comment]
新版本导致微信无法启动
都用最新版本

**Comment by aabb5605** [comment]
降级  可以解决
