### ISSUE TITLE
1.2.4版适配微信6.5.4对红包没反应

### ISSUE THREAD

**Issue by avjack** [veryyoung/WechatLuckyMoney#89]
重装了几次模块，重启了几次，微信群仍然不自动抢红包，免打扰确定是关闭的，仍然对红包没反应。

**Comment by aken85** [comment]
我的也是一样,重装过模块,也重新重装过xposed,找不到原因.用其他点击抢的模块就没有问题,但速度没这个快.郁闷.

**Comment by 52nome** [comment]
可以尝试降低微信版本然后也降低插件版本

**Comment by aken85** [comment]
我的是6.4.3无效看到更新了才升级的,还是一样无效,不知道是什么原因

**Comment by MrLiwg123** [comment]
手机要越狱吗？

**Comment by walaoaaa1234** [comment]
``Found wechat version:6.5.4
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1300(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5166)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:204)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/luckymoney/c/ae
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.c.ae" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 23 more
``

**Comment by falseen** [comment]
没有找到指定的类，可能是微信对后续发布的文件做了更改。我这里是可以用的。

可以尝试下载早期发布的6.5.4，如果找不到的话我可以提供一份

**Comment by zhiguicai** [comment]
02-23 14:47:56.216 1917-1917/com.tencent.mm I/Xposed: Found wechat version:6.5.4
02-23 14:47:56.220 1917-1917/com.tencent.mm I/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
                                                          at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
                                                          at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
                                                          at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Main.java:164)
                                                          at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
                                                          at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
                                                          at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
                                                          at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
                                                          at android.app.ActivityThread.handleBindApplication(Native Method)
                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:136)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                          at dalvik.system.NativeStart.main(Native Method)
                                                       Caused by: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
                                                          at java.lang.Class.classForName(Native Method)
                                                          at java.lang.Class.forName(Class.java:251)
                                                          at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
                                                          at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
                                                          at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136) 
                                                          at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Main.java:164) 
                                                          at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20) 
                                                          at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34) 
                                                          at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70) 
                                                          at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208) 
                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611) 
                                                          at android.app.ActivityThread.handleBindApplication(Native Method) 
                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:136) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                       Caused by: java.lang.NoClassDefFoundError: com/tencent/mm/plugin/luckymoney/c/ae
                                                          at java.lang.Class.classForName(Native Method) 
                                                          at java.lang.Class.forName(Class.java:251) 
                                                          at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823) 
                                                          at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50) 
                                                          at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136) 
                                                          at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Main.java:164) 
                                                          at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20) 
                                                          at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34) 
                                                          at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70) 
                                                          at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208) 
                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611) 
                                                          at android.app.ActivityThread.handleBindApplication(Native Method) 
                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:136) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.luckymoney.c.ae" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.tencent.mm-1, /system/lib]]
                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                          at java.lang.Class.classForName(Native Method) 
                                                          at java.lang.Class.forName(Class.java:251) 
                                                          at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823) 
                                                          at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50) 
                                                          at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136) 
                                                          at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Main.java:164) 
                                                          at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20) 
                                                          at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34) 
                                                          at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70) 
                                                          at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208) 
                                                          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611) 
                                                          at android.app.ActivityThread.handleBindApplication(Native Method) 
                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                          at android.os.Looper.loop(Looper.java:136) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by veryyoung** [comment]
@walaoaaa1234 @zhiguicai 可能是微信热发了吧，退回到 6.5.3，或者等6.5.5发布吧。

**Comment by aviraxp** [comment]
这个还真不是热发，而是腾讯发了两个6.5.4版。。。

**Comment by veryyoung** [comment]
@aviraxp 这样发布版本发布得算重大事故了吧...

**Comment by falseen** [comment]
难道只是为了防止红包插件 ？

**Comment by veryyoung** [comment]
@falseen 肯定不会，我这啥都不算。他们发版一次会走很严格的流程，像这种发版事故，内部估计会重罚的。

**Comment by mbq168** [comment]
你好 为什么我用android studio打包不了源文件啊 
老提示Error:Failed to resolve: com.crystal:crystalrangeseekbar:1.1.1 
我是新手不知道这是什么意思 麻烦大神说下 谢了

**Comment by falseen** [comment]
@mbq168 
这个问题已经修复了吧 ，你的还有问题 ？是用的最新的源码吗 ？

**Comment by limkaz** [comment]
我用不到的，抢不到😫😫

**Comment by lovefrr** [comment]
03-13 20:51:46.356 I/Xposed  (  305): -----------------
03-13 20:51:46.356 I/Xposed  (  305): Starting Xposed version 87 (MIUI edition by SolarWarez / 20161126), compiled for SDK 23
03-13 20:51:46.356 I/Xposed  (  305): Device: MI 4LTE (Xiaomi), Android version 6.0.1 (SDK 23)
03-13 20:51:46.356 I/Xposed  (  305): ROM: MMB29M
03-13 20:51:46.356 I/Xposed  (  305): Build fingerprint: Xiaomi/cancro_wc_lte/cancro:6.0.1/MMB29M/7.3.9:user/release-keys
03-13 20:51:46.356 I/Xposed  (  305): Platform: armeabi-v7a, 32-bit binary, system server: yes
03-13 20:51:46.356 I/Xposed  (  305): SELinux enabled: yes, enforcing: yes
03-13 20:51:47.375 I/Xposed  (  305): -----------------
03-13 20:51:47.375 I/Xposed  (  305): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-13 20:51:47.748 I/Xposed  (  305): Detected ART runtime
03-13 20:51:47.773 I/Xposed  (  305): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-13 20:51:47.796 I/Xposed  (  305): MIUI detected... Make some patch...
03-13 20:51:47.796 I/Xposed  (  305): All done!
03-13 20:51:48.670 I/Xposed  (  305): Loading modules from /data/app/com.fkzhang.wechatxposed-1/base.apk
03-13 20:51:48.695 I/Xposed  (  305):   Loading class com.fkzhang.wechatxposed.XposedInit
03-13 20:51:48.707 I/Xposed  (  305): Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1/base.apk
03-13 20:51:48.725 I/Xposed  (  305):   Loading class me.veryyoung.wechat.luckymoney.Main
03-13 20:51:48.727 E/Xposed  (  305):     Failed to load class me.veryyoung.wechat.luckymoney.Main
03-13 20:51:48.727 E/Xposed  (  305): java.lang.ClassNotFoundException: Didn't find class "me.veryyoung.wechat.luckymoney.Main" on path: DexPathList[[zip file "/data/app/me.veryyoung.wechat.luckymoney-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-13 20:51:48.727 E/Xposed  (  305): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-13 20:51:48.727 E/Xposed  (  305): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-13 20:51:48.727 E/Xposed  (  305): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-13 20:51:48.727 E/Xposed  (  305): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:1281)
03-13 20:51:48.727 E/Xposed  (  305): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:1211)
03-13 20:51:48.727 E/Xposed  (  305): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
03-13 20:51:48.727 E/Xposed  (  305): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "me.veryyoung.wechat.luckymoney.Main" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-13 20:51:48.727 E/Xposed  (  305): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-13 20:51:48.727 E/Xposed  (  305): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-13 20:51:48.727 E/Xposed  (  305): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-13 20:51:48.727 E/Xposed  (  305): 		... 4 more
03-13 20:51:48.727 E/Xposed  (  305): 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "me.veryyoung.wechat.luckymoney.Main" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-13 20:51:48.727 E/Xposed  (  305): 			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-13 20:51:48.727 E/Xposed  (  305): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-13 20:51:48.727 E/Xposed  (  305): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-13 20:51:48.727 E/Xposed  (  305): 			... 5 more
03-13 20:51:48.727 E/Xposed  (  305): 			Suppressed: java.lang.ClassNotFoundException: me.veryyoung.wechat.luckymoney.Main
03-13 20:51:48.727 E/Xposed  (  305): 				at java.lang.Class.classForName(Native Method)
03-13 20:51:48.727 E/Xposed  (  305): 				at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-13 20:51:48.727 E/Xposed  (  305): 				at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-13 20:51:48.727 E/Xposed  (  305): 				at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-13 20:51:48.727 E/Xposed  (  305): 				... 6 more
03-13 20:51:48.727 E/Xposed  (  305): 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-13 20:52:20.657 I/Xposed  ( 3373): com.tencent.mm loading com.fkzhang.wechatxposed
03-13 20:52:30.772 I/Xposed  ( 5300): com.tencent.mm loading com.fkzhang.wechatxposed
03-13 20:52:34.703 I/Xposed  ( 5300): 微X模块 1.1_3.13 1
03-13 20:52:34.703 I/Xposed  ( 5300): com.fkzhang.wechatxposed (1.1): wechat version 6.5.4(1000)
03-13 20:52:36.134 I/Xposed  ( 5884): com.tencent.mm loading com.fkzhang.wechatxposed
03-13 20:52:40.333 I/Xposed  ( 5884): 微X模块 1.1_3.13 1
03-13 20:52:40.333 I/Xposed  ( 5884): com.fkzhang.wechatxposed (1.1): wechat version 6.5.4(1000)
03-13 20:52:44.059 I/Xposed  ( 6355): com.tencent.mm loading com.fkzhang.wechatxposed
03-13 20:52:47.104 I/Xposed  ( 6355): 微X模块 1.1_3.13 1
03-13 20:52:47.105 I/Xposed  ( 6355): com.fkzhang.wechatxposed (1.1): wechat version 6.5.4(1000)
03-13 20:53:19.582 I/Xposed  ( 8219): com.tencent.mm loading com.fkzhang.wechatxposed
03-13 20:53:22.897 I/Xposed  ( 8219): 微X模块 1.1_3.13 1
03-13 20:53:22.897 I/Xposed  ( 8219): com.fkzhang.wechatxposed (1.1): wechat version 6.5.4(1000)
03-13 20:58:49.342 I/XposedInstaller( 8903): ModuleUtil -> updating modules.list
03-13 21:09:44.863 I/XposedInstaller(11852): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/11777.xml.gz with status 0 (error: null), size 2057 bytes
03-13 21:09:44.915 I/XposedInstaller(11852): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 11780 (2 new / 0 removed modules)

**Comment by falseen** [comment]
@lovefrr 
兄弟，你用了微X模块，可能会有冲突。

**Comment by lovefrr** [comment]
@falseen 我只保留这个插件也不行，不知道是不是手机问题，你的可以吗？

03-13 20:51:48.725 I/Xposed ( 305): Loading class me.veryyoung.wechat.luckymoney.Main
03-13 20:51:48.727 E/Xposed ( 305): Failed to load class me.veryyoung.wechat.luckymoney.Main
03-13 20:51:48.727 E/Xposed ( 305): java.lang.ClassNotFoundException: Didn't find class "me.veryyoung.wechat.luckymoney.Main" on path: DexPathList[[zip file "/data/app/me.veryyoung.wechat.luckymoney-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by veryyoung** [comment]
@lovefrr 类没加载上，卸载重来吧

**Comment by falseen** [comment]
@lovefrr
我是两个一起用的，没发现问题。
其实微x模块也有抢红包的功能，你要是用它的话就没必要用这个插件了。
